# Generated by Django 4.0.3 on 2022-03-19 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leitor_arquivos', '0002_diretorioss3_diretório'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diretorioss3',
            old_name='diretório',
            new_name='diretorio',
        ),
    ]
