# Generated by Django 4.0.3 on 2022-03-19 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leitor_arquivos', '0003_rename_diretório_diretorioss3_diretorio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diretorioss3',
            name='diretorio',
        ),
    ]
