# Generated by Django 4.0.3 on 2022-03-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitor_arquivos', '0004_remove_diretorioss3_diretorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='diretorioss3',
            name='diretorio',
            field=models.CharField(default='media/', max_length=150),
        ),
    ]
