# Generated by Django 4.0.3 on 2022-03-19 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leitor_arquivos', '0005_diretorioss3_diretorio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diretorioss3',
            old_name='diretorio',
            new_name='pasta',
        ),
    ]
