# Generated by Django 4.0.3 on 2022-03-20 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitor_arquivos', '0006_rename_diretorio_diretorioss3_pasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diretorioss3',
            name='arquivo',
            field=models.FileField(upload_to='media/temp/'),
        ),
    ]
